spring.application.name=e_commerce_api

spring.datasource.url=jdbc:mysql://localhost:3306/monk_commerce

spring.datasource.username=username*

spring.datasource.password=#####Password

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

#swagger api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
